# Generated by Django 5.2.12 on 2026-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('fare', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('eta', models.CharField(max_length=20)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='rider',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
