# Generated by Django 5.2.12 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ridebooking_remove_ride_driver_remove_ride_rider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('profile_pic', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
