# Generated by Django 5.2.12 on 2026-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rideuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideuser',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='rideuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='rideuser',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rideuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
