# Generated by Django 5.2.12 on 2026-04-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_rideuser_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='api.rideuser'),
        ),
    ]
