# Generated by Django 5.2.12 on 2026-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ridebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='destination_location',
            field=models.CharField(default='Unknown End', max_length=255),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='pickup_location',
            field=models.CharField(default='Unknown Start', max_length=255),
        ),
    ]
